### PR TITLE
Remove the binary file kpp_standalone.exe from the kpp-standalone branch

### PR DESCRIPTION
**Pull request by yantosca**
This PR removes the kpp_standalone.exe file from the `kpp_standalone` branch.  Typically it is not a good idea to track large binary files in Git.  Also this could lead to confusion if someone tries to run the executable on a different OS environment.

This was done with the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) with the following commands:

```console
$ java -jar ~/bin/bfg-1.14.0.jar --delete-files kpp_standalone.exe
$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

### CODE REVIEW

**Review by obin1 — APPROVED** [review]
Sounds good, thanks @yantosca! Should we add .exe to .gitignore?

**Comment by yantosca** [comment]
@obin1: Now fixed in commit db68908c5ea51a6f08cc40a5223804f4237b3487

**Comment by yantosca** [comment]
Oops, forgot to remove the file first.  Will push again.

**Comment by yantosca** [comment]
@obin1: Now all set.  Feel free to merge in at your leisure.

**Comment by obin1** [comment]
@yantosca sorry if this is a basic question, but do you know what is causing the merge conflicts? I tried manually deleting kpp_standalone.exe but that didn't seem to fix the conflicts in this PR, even though the changes are quite small

**Comment by yantosca** [comment]
@obin1, I was able to merge and force-push the updates.  The kpp_standalone.exe file is now removed, if you look at the kpp_standalone branch.

You will probably have to re-clone the repo to get the updated refs.  We can close out this PR now.

**Pull request closed without merging**
